version: "3"

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 9004:80
    volumes:
      - ./build:/var/www/html/
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - lego-front-network
networks:
  lego-front-network:
